export { asignacionesService } from './asignaciones';
export { authService } from './authService';
export { citasService } from './citas';
export { documentosService } from './documentos';
export { especialidadesService } from './especialidades';
export { especialistasService } from './especialistas';
export { evaluacionesService } from './evaluaciones';
export { fichasService } from './fichas';
export { institucionesService } from './instituciones';
export { pacientesService } from './pacientes';
export { pasantesService } from './pasantes';
export { sedesService } from './sedes';
export { seguimientosService } from './seguimientos';
export * from './recursos';