import React from "react";
import Switch from "../../../switch/Switch";

interface EvaluacionLenguajeProps {
  data: any;
  onChange: (field: string, value: any) => void;
}

const EvaluacionLenguajeForm: React.FC<EvaluacionLenguajeProps> = ({ data, onChange }) => {
  const fields = [
    { id: "palabrasRaras", label: "Palabras raras" },
    { id: "logicoYClaro", label: "Lógico y claro" },
    { id: "vozMonotona", label: "Voz monótona" },
    { id: "malHablado", label: "Mal hablado" },
    { id: "lentoYTeatral", label: "Lento y teatral" },
    { id: "pesimista", label: "Pesimista" },
    { id: "hiriente", label: "Hiriente" },
    { id: "charlatan", label: "Charlatán" },
    { id: "incoherente", label: "Incoherente" },
    { id: "verborrea", label: "Verborrea" },
    { id: "abatimiento", label: "Abatimiento" },
    { id: "tension", label: "Tensión" },
    { id: "perplejidad", label: "Perplejidad" },
    { id: "suspicacia", label: "Suspicacia" },
    { id: "enfado", label: "Enfado" },
    { id: "preocupacion", label: "Preocupación" },
    { id: "obscenidad", label: "Obscenidad" },
    { id: "disartria", label: "Disartria" },
    { id: "afasiaExpresiva", label: "Afasia expresiva" },
    { id: "afasiaReceptiva", label: "Afasia receptiva" },
    { id: "afasiaAnomica", label: "Afasia anómica" },
    { id: "afasiaGlobal", label: "Afasia global" },
    { id: "ecolalia", label: "Ecolalia" },
    { id: "palilalia", label: "Palilalia" },
    { id: "ensimismamiento", label: "Ensimismamiento" },
    { id: "hayQueGuiarlo", label: "Hay que guiarlo" },
    { id: "molestoso", label: "Molestoso" },
    { id: "lento", label: "Lento" },
    { id: "noDeseaHacerNada", label: "No desea hacer nada" },
    { id: "haceCosasExtranas", label: "Hace cosas extrañas" },
    { id: "aislado", label: "Aislado" },
    { id: "participaEnGrupos", label: "Participa en grupos" },
    { id: "esViolento", label: "Es violento" },
    { id: "callado", label: "Callado" },
    { id: "amigableYCooperador", label: "Amigable y cooperador" },
    { id: "adaptable", label: "Adaptable" },
    { id: "inquieto", label: "Inquieto" },
    { id: "nervioso", label: "Nervioso" },
    { id: "tieneAmigosIntimos", label: "Tiene amigos íntimos" },
    { id: "confuso", label: "Confuso" },
    { id: "centradoEnSiMismo", label: "Centrado en sí mismo" },
    { id: "olvidadizo", label: "Olvidadizo" },
    { id: "piensaYRespondeBien", label: "Piensa y responde bien" },
    { id: "pocosPensamientos", label: "Pocos pensamientos" },
    { id: "noVeLosErrores", label: "No ve los errores" },
    { id: "actuaInfaltilmente", label: "Actúa infantilmente" },
    { id: "desconfia", label: "Desconfía" },
    { id: "hosco", label: "Hosco" },
    { id: "fastidiado", label: "Fastidiado" },
    { id: "cansado", label: "Cansado" },
    { id: "visteRaramente", label: "Viste raramente" },
    { id: "desordenado", label: "Desordenado" },
    { id: "mugrosoYFachoso", label: "Mugroso y fachoso" },
    { id: "excesoDeRopas", label: "Exceso de ropas" },
    { id: "dramaticoYTeatral", label: "Dramático y teatral" },
    { id: "visteNormalmente", label: "Viste normalmente" },
    { id: "impecable", label: "Impecable" },
    { id: "dudaDeTodos", label: "Duda de todos" },
    { id: "pasaAislado", label: "Pasa aislado" },
    { id: "diceEstarBien", label: "Dice estar bien" },
    { id: "gustaDeHacerDanoALosDemas", label: "Gusta de hacer daño a los demás" },
    { id: "tieneIniciativas", label: "Tiene iniciativas" },
    { id: "colabora", label: "Colabora" },
    { id: "reticencia", label: "Reticencia" },
    { id: "rechazo", label: "Rechazo" },
    { id: "mutismo", label: "Mutismo" },
    { id: "negativismo", label: "Negativismo" },
    { id: "agresividad", label: "Agresividad" },
    { id: "sarcasmo", label: "Sarcasmo" },
    { id: "pegajosidad", label: "Pegajosidad" },
    { id: "colaboracionExcesiva", label: "Colaboración excesiva" },
    { id: "atento", label: "Atento" },
    { id: "seductor", label: "Seductor" },
    { id: "evitaConversar", label: "Evita conversar" },
    { id: "impulsivo", label: "Impulsivo" },
    { id: "bromista", label: "Bromista" },
    { id: "toscoYDescortes", label: "Tosco y descortés" },
    { id: "triste", label: "Triste" },
    { id: "irritable", label: "Irritable" },
    { id: "popensoARinias", label: "Propenso a riñas" },
    { id: "suaveYAfable", label: "Suave y afable" },
    { id: "indiferente", label: "Indiferente" },
    { id: "preocupadoYPensativo", label: "Preocupado y pensativo" },
    { id: "tendenciaAlLlanto", label: "Tendencia al llanto" },
    { id: "alegre", label: "Alegre" },
    { id: "euforico", label: "Euforico" },
    { id: "labilDeHumor", label: "Lábil de humor" },
    { id: "inactivo", label: "Inactivo" },
    { id: "perezoso", label: "Perezoso" },
    { id: "soloHaceCosasIndispensables", label: "Solo hace cosas indispensables" },
    { id: "realizaSoloUnTipoDeTrabajo", label: "Realiza solo un tipo de trabajo" },
    { id: "dedicadoAVariasActividades", label: "Dedicado a varias actividades" },
    { id: "apraxia", label: "Apraxia" },
    { id: "catatonia", label: "Catatonia" },
    { id: "agitacion", label: "Agitación" },
    { id: "amaneramiento", label: "Amaneramiento" },
    { id: "estereotipias", label: "Estereotipias" },
    { id: "ecopraxia", label: "Ecopraxia" },
    { id: "obedienciaAutomatica", label: "Obediencia automática" },
    { id: "negativismoActividades", label: "Negativismo actividades" },
    { id: "interceptacionMotriz", label: "Interceptación motriz" },
    { id: "dispraxias", label: "Dispraxias" },
    { id: "actosImpulsivos", label: "Actos impulsivos" },
    { id: "actosObsesivos", label: "Actos obsesivos" },
    { id: "ticsActividades", label: "Tics actividades" },
    { id: "liderazgo", label: "Liderazgo" },
    { id: "sociabilidad", label: "Sociabilidad" },
    { id: "responsabilidad", label: "Responsabilidad" },
    { id: "toleranciaNormal", label: "Tolerancia normal" },
    { id: "baja", label: "Baja" },
    { id: "colaboracion", label: "Colaboración" },
    { id: "inquietud", label: "Inquietud" },
    { id: "acataOrdenesVerbales", label: "Acata órdenes verbales" },
    { id: "agresivo", label: "Agresivo" },
    { id: "extravagante", label: "Extravagante" },
    { id: "antisocial", label: "Antisocial" },
    { id: "impulsivoComportamiento", label: "Impulsivo comportamiento" },
    { id: "reflexivo", label: "Reflexivo" },
    { id: "pasivo", label: "Pasivo" },
    { id: "apatico", label: "Apático" },
    { id: "dependiente", label: "Dependiente" },
    { id: "dominante", label: "Dominante" },
    { id: "cauteloso", label: "Cauteloso" },
    { id: "quejoso", label: "Quejoso" },
    { id: "temeroso", label: "Temeroso" },
    { id: "teatral", label: "Teatral" },
    { id: "ritualista", label: "Ritualista" },
    { id: "aislamiento", label: "Aislamiento" },
    { id: "ataquesDePanico", label: "Ataques de pánico" },
    { id: "incapacidadDeRealizacionDeActividadesProductivas", label: "Incapacidad de realización de actividades productivas" },
    { id: "riesgoPotencialOPotencialSuicida", label: "Riesgo potencial o potencial suicida" },
    { id: "inhibicion", label: "Inhibición" },
    { id: "apatia", label: "Apatía" },
    { id: "humorVariable", label: "Humor variable" },
  ];

  return (
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      {fields.map((field) => (
        <Switch
          key={field.id}
          label={field.label}
          checked={data[field.id]}
          onChange={(checked: boolean) => onChange(field.id, checked)}
        />
      ))}
    </div>
  );
};

export default EvaluacionLenguajeForm;
